name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "37 13 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open for 1 week with no activity. Remove stale label or comment or this will be closed in 5 days.'
        stale-pr-message: 'This pr is stale because it has been open 1 week with no activity. Remove stale label or comment or this will be closed in 5 days.'
        close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
        close-pr-message: 'This pr was closed because it has been stalled for 5 days with no activity.'
        days-before-stale: 7
        days-before-close: 5
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
